Added Time and Status widgets
EnderWiggin/hafen-client pull request #134
Opened 2024-11-16 22:17 UTC by AlexKondor

2024-11-16 22:55 UTC, AlexKondor commented
Added inventories sorter

2024-11-18 04:34 UTC, AlexKondor commented
Quest markers for questhelper.
It works well, but need merge refresh + refactor some old variables and optimize.
![image](https://github.com/user-attachments/assets/087e2358-2344-4b94-b07b-650f40493dc0)

2024-11-20 01:32 UTC, AlexKondor commented
Totally remastered QuestHelper. Now works smoothly and without bugs.
Tested:
new quests
remove quests
update states of quest conditions
finish quests
![image](https://github.com/user-attachments/assets/334d2737-2915-4856-978b-99f81ebfc856)

2024-11-20 01:34 UTC, AlexKondor commented
Also fix rectangles
![image](https://github.com/user-attachments/assets/7a8269b9-127a-43c9-865e-e7b7d23d7422)
![image](https://github.com/user-attachments/assets/4247e06f-d801-47cb-91f5-397200e30bc4)

2024-11-22 14:09 UTC, AlexKondor commented
I hope i'm done.

Anyway one issue... Credo conditions like "Eat x something" changes description for each eat. Not a real problem, but anyway.
Possible solution - just rewrite all conditions everytime... or using patterns for search.

2024-11-29 16:31 UTC, EnderWiggin commented
I would really prefer if all these changes were separate requests. Wil try to make sense of all of this.

2024-11-29 19:11 UTC, EnderWiggin requested changes

2024-11-30 04:46 UTC, AlexKondor commented on src/haven/ExtInventory.java
> +		wnd.addtwdg(btn_sort);
which one list? It's already check !disabled, that uses needDisableExtraInventory for exclude.
EXCLUDES from InventorySorter are used for SortAll.

2024-11-30 06:36 UTC, AlexKondor commented on src/auto/InventorySorter.java
> +	    return a > 0 ? name.substring(a + (name.contains("seeds") ? 5 : 4)) : name;
yes, its sorts seeds, just this fix problem than 1 seed, 2 seeds

2024-11-30 06:54 UTC, EnderWiggin commented on src/haven/ExtInventory.java
> +		wnd.addtwdg(btn_sort);
I see sort buttons on Kilns, for example, which can't be sorted. At least not ready products.

2024-11-30 08:14 UTC, AlexKondor commented on src/haven/ExtInventory.java
> +		wnd.addtwdg(btn_sort);
Not bug, but feature, it can be sorted by click on sort button, but can't be sorted by SortAll keybind.
better remove this?

2024-11-30 08:22 UTC, AlexKondor commented on src/auto/InventorySorter.java
> +	    return item.item.resname();
this was for tests. Actual name have alot of restricts, like plural names etc.

2024-11-30 10:28 UTC, AlexKondor commented on src/haven/GameUI.java
> +	statuswdg = add(new StatusWdg());
Lately possible to rework it. Now just some optimize.

2024-11-30 12:08 UTC, EnderWiggin commented
Sorry, I've got a bit impatient and took inventory sorting from your PR into beta branch myself. I'm closing this PR without merging, but please submit new PR's with other changes from this one.

2024-11-30 12:08 UTC, closed without merging